-- ============================================================================
-- TokMieja Shop - Phase 3: secure order creation
-- ----------------------------------------------------------------------------
-- HOW TO RUN
--   Supabase Dashboard -> SQL Editor -> New query -> paste -> Run.
--   Run this AFTER supabase/schema.sql (and optionally seed.sql).
--
-- Safe to re-run.
--
-- WHAT THIS DOES
--   1. Adds `orders.idempotency_key` so the same checkout submission cannot
--      create duplicate orders.
--   2. Adds a database-side order-number sequence (TM-YYYYMMDD-XXX).
--   3. Adds a SECURITY DEFINER function `create_order(...)` that is the ONLY
--      way customers can create orders. It re-reads products from the
--      database, validates active/stock, prices everything server-side, writes
--      orders + order_items, and decrements stock atomically.
--
-- SECURITY NOTES
--   * RLS on orders/order_items is unchanged: there is still NO public INSERT
--     policy. Direct client inserts remain impossible.
--   * The function runs with definer privileges (owned by the role that runs
--     this file, normally `postgres`), so it can insert while customers cannot.
--   * EXECUTE is revoked from PUBLIC and granted only to anon + authenticated.
--   * The internal summary helper is not callable by anon.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Order-number sequence (database-side, never generated by the browser)
-- ----------------------------------------------------------------------------
create sequence if not exists public.order_number_seq start with 1 increment by 1;

revoke all on sequence public.order_number_seq from public;

-- ----------------------------------------------------------------------------
-- Idempotency key for duplicate-submission protection
-- ----------------------------------------------------------------------------
alter table public.orders add column if not exists idempotency_key text;

create unique index if not exists orders_idempotency_key_key
  on public.orders (idempotency_key)
  where idempotency_key is not null;

-- ----------------------------------------------------------------------------
-- Internal helper: build the sanitized confirmation payload for an order.
-- Not callable by anon (execute is revoked below); used by create_order.
-- ----------------------------------------------------------------------------
create or replace function public.build_order_summary(p_order public.orders)
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select jsonb_build_object(
    'order_number', p_order.order_number,
    'customer_name', p_order.customer_name,
    'status', p_order.status,
    'subtotal', p_order.subtotal,
    'delivery_fee', p_order.delivery_fee,
    'total', p_order.total,
    'created_at', p_order.created_at,
    'items', coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'name', oi.product_name,
            'quantity', oi.quantity,
            'unit_price', oi.unit_price,
            'subtotal', oi.subtotal
          )
          order by oi.created_at
        )
        from public.order_items oi
        where oi.order_id = p_order.id
      ),
      '[]'::jsonb
    )
  );
$$;

revoke all on function public.build_order_summary(public.orders) from public;

-- ----------------------------------------------------------------------------
-- create_order: the ONLY customer order-creation path.
-- ----------------------------------------------------------------------------
create or replace function public.create_order(
  p_customer_name text,
  p_customer_phone text,
  p_customer_email text,
  p_delivery_address text,
  p_notes text,
  p_items jsonb,
  p_idempotency_key text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_existing public.orders%rowtype;
  v_order_id uuid;
  v_order_number text;
  v_subtotal numeric(10, 2) := 0;
  v_delivery_fee numeric(10, 2) := 0;   -- Phase 3: delivery fee is not calculated yet.
  v_total numeric(10, 2) := 0;
  v_line numeric(10, 2);
  v_item jsonb;
  v_product public.products%rowtype;
  v_product_id uuid;
  v_qty integer;
  v_item_count integer := 0;
  v_lines jsonb := '[]'::jsonb;
  v_key text;
begin
  -- --- validate customer input -------------------------------------------
  if p_customer_name is null or length(btrim(p_customer_name)) < 2 then
    raise exception 'NAMA_REQUIRED';
  end if;

  if p_customer_phone is null
     or length(regexp_replace(p_customer_phone, '[^0-9]', '', 'g')) < 8 then
    raise exception 'TELEFON_REQUIRED';
  end if;

  if p_delivery_address is null or length(btrim(p_delivery_address)) < 5 then
    raise exception 'ALAMAT_REQUIRED';
  end if;

  if p_items is null
     or jsonb_typeof(p_items) <> 'array'
     or jsonb_array_length(p_items) = 0 then
    raise exception 'TIADA_ITEM';
  end if;

  if jsonb_array_length(p_items) > 50 then
    raise exception 'TERLALU_BANYAK_ITEM';
  end if;

  v_key := nullif(btrim(coalesce(p_idempotency_key, '')), '');

  -- --- idempotency: return the existing order for a repeated submission ---
  if v_key is not null then
    select * into v_existing
      from public.orders
      where idempotency_key = v_key;

    if found then
      return public.build_order_summary(v_existing);
    end if;
  end if;

  -- --- order number (server side only) -----------------------------------
  v_order_number :=
    'TM-'
    || to_char(timezone('Asia/Kuala_Lumpur', now()), 'YYYYMMDD')
    || '-'
    || lpad(nextval('public.order_number_seq')::text, 3, '0');

  -- --- create the order header first (totals filled in below) ------------
  begin
    insert into public.orders (
      order_number,
      customer_name,
      customer_phone,
      customer_email,
      delivery_address,
      notes,
      subtotal,
      delivery_fee,
      total,
      status,
      idempotency_key
    )
    values (
      v_order_number,
      btrim(p_customer_name),
      btrim(p_customer_phone),
      nullif(btrim(coalesce(p_customer_email, '')), ''),
      btrim(p_delivery_address),
      nullif(btrim(coalesce(p_notes, '')), ''),
      0,
      0,
      0,
      'pending',
      v_key
    )
    returning id into v_order_id;
  exception
    when unique_violation then
      -- Concurrent duplicate submission with the same idempotency key.
      select * into v_existing
        from public.orders
        where idempotency_key = v_key;

      if found then
        return public.build_order_summary(v_existing);
      end if;
      raise;
  end;

  -- --- validate + price every line from the database ---------------------
  for v_item in select value from jsonb_array_elements(p_items)
  loop
    begin
      v_product_id := (v_item ->> 'product_id')::uuid;
    exception
      when others then
        raise exception 'PRODUK_TIDAK_DITEMUI';
    end;

    begin
      v_qty := (v_item ->> 'quantity')::int;
    exception
      when others then
        raise exception 'KUANTITI_TIDAK_SAH';
    end;

    if v_qty is null or v_qty < 1 or v_qty > 99 then
      raise exception 'KUANTITI_TIDAK_SAH';
    end if;

    -- Lock the product row to prevent overselling under concurrency.
    select * into v_product
      from public.products
      where id = v_product_id
      for update;

    if not found then
      raise exception 'PRODUK_TIDAK_DITEMUI';
    end if;

    if v_product.active is not true then
      raise exception 'PRODUK_TIDAK_AKTIF';
    end if;

    if v_product.stock_quantity < v_qty then
      raise exception 'STOK_TIDAK_CUKUP';
    end if;

    -- Database price is the source of truth.
    v_line := v_product.price * v_qty;
    v_subtotal := v_subtotal + v_line;

    insert into public.order_items (
      order_id,
      product_id,
      product_name,
      unit_price,
      quantity,
      subtotal
    )
    values (
      v_order_id,
      v_product.id,
      v_product.name,        -- purchase-time snapshot
      v_product.price,       -- purchase-time snapshot
      v_qty,
      v_line
    );

    update public.products
      set stock_quantity = stock_quantity - v_qty
      where id = v_product.id;

    v_lines := v_lines || jsonb_build_object(
      'name', v_product.name,
      'quantity', v_qty,
      'unit_price', v_product.price,
      'subtotal', v_line
    );

    v_item_count := v_item_count + v_qty;
  end loop;

  v_total := v_subtotal + v_delivery_fee;

  update public.orders
    set subtotal = v_subtotal,
        delivery_fee = v_delivery_fee,
        total = v_total
    where id = v_order_id;

  return jsonb_build_object(
    'order_number', v_order_number,
    'customer_name', btrim(p_customer_name),
    'status', 'pending',
    'subtotal', v_subtotal,
    'delivery_fee', v_delivery_fee,
    'total', v_total,
    'item_count', v_item_count,
    'created_at', now(),
    'items', v_lines
  );
end;
$$;

-- Only anon/authenticated customers may place orders through this function.
revoke all on function public.create_order(
  text, text, text, text, text, jsonb, text
) from public;

grant execute on function public.create_order(
  text, text, text, text, text, jsonb, text
) to anon, authenticated;

-- ============================================================================
-- Done. Verify with:
--   select routine_name from information_schema.routines
--   where routine_schema = 'public' and routine_name = 'create_order';
-- ============================================================================
